//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WATaskAssignment
    {
        public int AssignmentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public string Status { get; set; }
    
        public virtual WATask WATask { get; set; }
        public virtual WAUser WAUser { get; set; }
    }
}
